/*
NAME: BASAVARAJA BN
DATA: 8/10/2024
DESCIPTION: LSB Image Steganography 
-------------------------------------------
SAMPLE IP FOR ENCODE:
./a.out -e beautiful.bmp secret.txt
-----------------------------------------------
SAMPLE OP FOR ENCODE:
EODING PROCESS STARTED
STEP 1 :  OPEN FILES GETS SUCCESS
STEP 2 : CHECK_CAPACITY_ GETS SUCCESS
STEP 3 : COPY_BMP_HEADER GETS SUCCESS
STEP 4 : ENCODE_MAGIC_STRING SUCCESS
STEP 5 : SECRET FILE EXTENTION SIZE ENCODED SUCCESFULLY
STEP 6 : SECRET FILE EXTENTION SUCCESFULLY
STEP 7 : SECRET FILE SIZE ENCODEED SUCCESFULLY
STEP 8 : SECRET FILE DATA ENCODED SUCCESFULLY
STEP 9 : COPY IMG DATA SUCCESFULLY
ENCODING SUCCESS
--------------------------------------------
SAMPLE IP FOR DECODE:
./a.out -d stego.bmp
-------------------------------------------
SAMPLE OP FOR DECODE:
DECODING PROCESS STARTED
STEP 1 : OPEN FILES GETS SUCCESS
STEP 2 : DECODE_MAGIC_STRING SUCCESS
STEP 3 : SECRET FILE EXTENTION SIZE DECODED SUCCESFULLY
STEP 4 : SECRET FILE EXTENTION SUCCESFULLY
STEP 5 : SECRET FILE SIZE DECODEED SUCCESFULLY
STEP 6 : SECRET FILE DATA DECODED SUCCESFULLY
DECODING SUCCESS
 */
#ifndef COMMON_H
#define COMMON_H

/* Magic string to identify whether stegged or not */
#define MAGIC_STRING "#*"

#endif
